### ISSUE TITLE
Wrong path to query files when running cli tool from subfolder

### ISSUE THREAD

**Issue by jo-jstrm** [jo-jstrm/SmartHomeBuddy#40]
**Describe the bug**
When running the cli tool from the device-identifier folder, it encounters an error, because the path to a query file is wrong. The program looks for `SmartHomeBuddy/device-identifier/device-identifier/shbdeviceidentifier/utilities/queries/get_all_devices.flux`, which should be `SmartHomeBuddy/device-identifier/shbdeviceidentifier/utilities/queries/get_all_devices.flux` instead.

**To Reproduce**
1. `cd device-identifier`
3. `shbdeviceidentifier`

**Expected behavior**
Device identifier starts without error.

**Desktop (please complete the following information):**
 - PopOS 22.04
 
**Additional context**
```bash
Traceback (most recent call last):
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/bin/shbdeviceidentifier", line 5, in <module>
    from shbdeviceidentifier import __main__
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/__init__.py", line 1, in <module>
    from shbdeviceidentifier import __main__
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/__main__.py", line 1, in <module>
    from .app import app
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/app.py", line 15, in <module>
    from .db import Database, DataLoader
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/db.py", line 21, in <module>
    from .utilities.app_utilities import resolve_file_path
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/utilities/__init__.py", line 3, in <module>
    from .queries import INFLUX_QUERIES, SQLITE_QUERIES, QUERIES
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/utilities/queries.py", line 12, in <module>
    'get_all_devices': query_file_to_string(q_path / 'get_all_devices.flux'),
  File "/home/jo/git/SmartHomeBuddy/device-identifier/.venv/lib/python3.8/site-packages/shbdeviceidentifier/utilities/queries.py", line 7, in query_file_to_string
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jo/git/SmartHomeBuddy/device-identifier/device-identifier/shbdeviceidentifier/utilities/queries/get_all_devices.flux'
```

**Comment by jo-jstrm** [comment]
My fix was to change q_path in queries.py to 
```python
q_path = Path("shbdeviceidentifier/utilities/queries").resolve()
```

But I am not aware, if this has any implications on other functionalities...

**Comment by jo-jstrm** [comment]
Update: There are other paths set that only work from the project root as well.

**Comment by TB-DevAcc** [comment]
> My fix was to change q_path in queries.py to
> 
> ```python
> q_path = Path("shbdeviceidentifier/utilities/queries").resolve()
> ```
> 
> But I am not aware, if this has any implications on other functionalities...

Making it relative from queries.py is likely the best idea and then resolving with resolve_file_path
