### ISSUE TITLE
Current Distributable does not start InfluxDB

### ISSUE THREAD

**Issue by jo-jstrm** [jo-jstrm/SmartHomeBuddy#56]
**Describe the bug**
The current distributable does not start the  Device Identifier and therefore also InfluxDB.

**To Reproduce**
1. Install SHB and run it
2. `pgrep influx` -> empty

**Expected behavior**
 Device Identifier and InfluxDB start.

**Desktop (please complete the following information):**
PopOS 22.04

**Comment by jo-jstrm** [comment]
Running the pyinstaller-compiled `./cli` throws and error.

```bash
Traceback (most recent call last):
  File "cli.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "shbdeviceidentifier/__init__.py", line 1, in <module>
ImportError: cannot import name '__main__' from partially initialized module 'shbdeviceidentifier' (most likely due to a circular import) (/usr/lib/smarthomebuddy/resources/cli/shbdeviceidentifier/__init__.pyc)
[9496] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by jo-jstrm** [comment]
Fixed the above error by outsourcing the Click-CLI code to cli.py. Now we run into issues when creating a binary with pyinstaller.

**Comment by jo-jstrm** [comment]
Fixed the problems.
